{
 "title": "Demo App Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Successful Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_ok", "legendFormat": "Successful Transactions" }
   ]
  },
  {
   "title": "Warnings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_warning", "legendFormat": "Warning Transactions" }
   ]
  },
  {
   "title": "Exceptions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_exception", "legendFormat": "Exception Transactions" }
   ]
  }
 ]
}