{
 "title": "PCP Vector Checklist: Memory",
 "tags": [
  "pcp-vector",
  "pcp-checklist"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "pcp-breadcrumbs-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Swapping [# of pages]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "swap_pagesout", "legendFormat": "{{hostname}} - swap_pagesout" }
   ]
  },
  {
   "title": "Low mm reclaim efficiency [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(mem_vmstat_pgsteal_direct[5m]) + rate(mem_vmstat_pgsteal_kswapd[5m])) / (rate(mem_vmstat_pgscan_direct[5m]) + rate(mem_vmstat_pgscan_kswapd[5m]))",
     "legendFormat": "$expr",
     "name": "vmeff"
    }
   ]
  },
  {
   "title": "Huge defragmentation [ops]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_vmstat_thp_fault_alloc",
     "legendFormat": "{{hostname}} - mem_vmstat_thp_fault_alloc"
    },
    {
     "expr": "mem_vmstat_thp_fault_fallback",
     "legendFormat": "{{hostname}} - mem_vmstat_thp_fault_fallback"
    },
    {
     "expr": "mem_vmstat_thp_collapse_alloc",
     "legendFormat": "{{hostname}} - mem_vmstat_thp_collapse_alloc"
    }
   ]
  },
  {
   "title": "Huge fragmentation [# of page splits]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_vmstat_thp_split",
     "legendFormat": "{{hostname}} - mem_vmstat_thp_split"
    }
   ]
  }
 ]
}