{
 "title": "PCP Vector Checklist: CPU",
 "tags": [
  "pcp-vector",
  "pcp-checklist"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "pcp-breadcrumbs-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Per-CPU busy (User) [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kernel_percpu_cpu_user", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  },
  {
   "title": "Per-CPU busy (System) [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kernel_percpu_cpu_sys", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  },
  {
   "title": "Kernel SamePage Merging Daemon (ksmd)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hotproc_psinfo_utime[5m]) + rate(hotproc_psinfo_stime[5m])",
     "legendFormat": "{{hostname}}",
     "name": "hotproc.psinfo.ksmd.util"
    }
   ]
  }
 ]
}