{
 "title": "PCP Vector Checklist: Network RX",
 "tags": [
  "pcp-vector",
  "pcp-checklist"
 ],
 "time": { "from": "2021-01-27T13:44:42.791Z", "to": "2021-01-27T13:54:42.791Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "pcp-breadcrumbs-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Saturation [# packet drops]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_interface_in_drops", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_interface_in_errors", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  },
  {
   "title": "Queue too small",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_softnet_dropped", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  },
  {
   "title": "packet processing exceeding time quota",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "network_softnet_time_squeeze", "legendFormat": "{{hostname}} - {{instname}}" }
   ]
  }
 ]
}