{
 "title": "PCP Vector Checklist",
 "tags": [
  "pcp-vector",
  "pcp-checklist"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "type": "pcp-breadcrumbs-panel", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_percpu_cpu_idle[5m])",
     "legendFormat": "{{hostname}} - cpu {{cpu}}",
     "name": "kernel.percpu.cpu.util.all"
    }
   ]
  },
  {
   "title": "Storage Utilization [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "disk_dev_avactive", "legendFormat": "{{hostname}} - {{instance}}" }
   ]
  },
  {
   "title": "Memory Utilization [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mem_util_available / mem_physmem",
     "legendFormat": "{{hostname}} - {{instance}}",
     "name": "mem.ratio.available"
    }
   ]
  },
  {
   "title": "Network TX Utilization [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_out_bytes[5m]) / network_interface_baudrate",
     "legendFormat": "{{hostname}} - {{instance}}",
     "name": "network_tx_bandwidth"
    }
   ]
  },
  {
   "title": "Network RX Utilization [%]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_in_bytes[5m]) / network_interface_baudrate",
     "legendFormat": "{{hostname}} - {{instance}}",
     "name": "network_rx_bandwidth"
    }
   ]
  }
 ]
}