{
 "title": "Quarkus Demo App Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Performed Checks",
   "type": "stat",
   "description": "How many primality checks have been performed.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_com_redhat_PrimeNumberChecker_performedChecks_total",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Highest Number",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "application_com_redhat_PrimeNumberChecker_highestPrimeNumberSoFar",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Checks Timer",
   "type": "graph",
   "description": "A measure of how long it takes to perform the primality test.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_redhat_PrimeNumberChecker_checksTimer_mean_seconds",
     "legendFormat": "project: {{namespace}} - pod: {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  }
 ]
}